### ISSUE TITLE
Wrong links in Gitlab codequality widget

### ISSUE THREAD

**Issue by zhukovra** [micheh/phpcs-gitlab#22]
Hi, @micheh.

Refer to [Gitlab documentation](https://docs.gitlab.com/13.8/ee/user/project/merge_requests/code_quality.html#implementing-a-custom-tool) location.path must be "relative path to the file containing the code quality violation"

![image](https://user-images.githubusercontent.com/289431/107568667-62e26e00-6bf8-11eb-8828-8a6d5d461574.png)

But now it is absolute path that generates in widget wrong links to source code.  
Example from my project, red line is base checkout path in runner:

![image](https://user-images.githubusercontent.com/289431/107568381-f4051500-6bf7-11eb-80b6-7c0a3c5704f3.png)

That part should be trimmed with `$CI_PROJECT_DIR` ([doc](https://docs.gitlab.com/13.8/ee/ci/variables/predefined_variables.html))
https://github.com/micheh/phpcs-gitlab/blob/fd64e6579d9e30a82abba616fabcb9a2c837c7a8/src/Report/Gitlab.php#L41

**Comment by micheh** [comment]
Hello @zhukovra 

Thank you for the report. But I'm not sure if this should be the responsibility of the report formatter. You can run PHP Code Sniffer with the `--basepath` argument (or in your phpcs.xml config, e.g. with `<arg name="basepath" value="."/>`) and it will remove the absolute path. 

Maybe this should be addressed by adding an info to the documentation, instead of removing the path in the formatter. What do you think?

**Comment by zhukovra** [comment]
@micheh you are right. Thank you, all works as expected.
